<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>false</UseWPF>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>snoopwpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta5.25306.1" />
    <PackageReference Include="System.Management" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfInspector\WpfInspector.csproj" />
    <ProjectReference Include="..\..\snoopwpf\Snoop.InjectorLauncher\Snoop.InjectorLauncher.csproj" />
  </ItemGroup>

</Project>
